# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rstepper_biv_c <- function(theta, r, bbox, iter, x0, dbg, toroidal) {
    .Call('rgeyer_rstepper_biv_c', PACKAGE = 'rgeyer', theta, r, bbox, iter, x0, dbg, toroidal)
}

rstepper_multi_c <- function(theta0, theta1_list, theta2_list, bbox, iter, x0, dbg, toroidal, trend_ims) {
    .Call('rgeyer_rstepper_multi_c', PACKAGE = 'rgeyer', theta0, theta1_list, theta2_list, bbox, iter, x0, dbg, toroidal, trend_ims)
}

rstepper_multi_fixed_c <- function(theta1_list, theta2_list, bbox, iter, x0, dbg, toroidal, trend_ims) {
    .Call('rgeyer_rstepper_multi_fixed_c', PACKAGE = 'rgeyer', theta1_list, theta2_list, bbox, iter, x0, dbg, toroidal, trend_ims)
}

rstepper_univ_c <- function(theta, r, bbox, iter, x0, dbg, toroidal, trend_im) {
    .Call('rgeyer_rstepper_univ_c', PACKAGE = 'rgeyer', theta, r, bbox, iter, x0, dbg, toroidal, trend_im)
}

rstepper_univ_fixed_c <- function(n, theta, r, bbox, iter, x0, dbg, toroidal, trend_im) {
    .Call('rgeyer_rstepper_univ_fixed_c', PACKAGE = 'rgeyer', n, theta, r, bbox, iter, x0, dbg, toroidal, trend_im)
}

rtest_classes_biv_c <- function(theta, r, bbox, iter, x0, dbg, toroidal) {
    .Call('rgeyer_rtest_classes_biv_c', PACKAGE = 'rgeyer', theta, r, bbox, iter, x0, dbg, toroidal)
}

rtest_classes_c <- function(theta, r, bbox, iter, x0, dbg, toroidal) {
    .Call('rgeyer_rtest_classes_c', PACKAGE = 'rgeyer', theta, r, bbox, iter, x0, dbg, toroidal)
}

rstepper_biv_components_c <- function(from, to, r, bbox, dbg, toroidal) {
    .Call('rgeyer_rstepper_biv_components_c', PACKAGE = 'rgeyer', from, to, r, bbox, dbg, toroidal)
}

rstepper_biv_components_at_data_c <- function(from, r, bbox, dbg, toroidal) {
    .Call('rgeyer_rstepper_biv_components_at_data_c', PACKAGE = 'rgeyer', from, r, bbox, dbg, toroidal)
}

rstepper_components_c <- function(from, to, r, bbox, dbg, toroidal) {
    .Call('rgeyer_rstepper_components_c', PACKAGE = 'rgeyer', from, to, r, bbox, dbg, toroidal)
}

rstepper_components_at_data_c <- function(from, r, bbox, dbg, toroidal) {
    .Call('rgeyer_rstepper_components_at_data_c', PACKAGE = 'rgeyer', from, r, bbox, dbg, toroidal)
}

rstepper_log_papangelou_c <- function(from, to, theta, r, bbox, dbg, toroidal) {
    .Call('rgeyer_rstepper_log_papangelou_c', PACKAGE = 'rgeyer', from, to, theta, r, bbox, dbg, toroidal)
}

rtest_graph_c <- function(x0, bbox, r) {
    .Call('rgeyer_rtest_graph_c', PACKAGE = 'rgeyer', x0, bbox, r)
}

rtest_im_c <- function(im, x) {
    .Call('rgeyer_rtest_im_c', PACKAGE = 'rgeyer', im, x)
}

